version: '3.8'

services:
  php:
    image: php:8.1-apache
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    platform: linux/amd64
    command: >
      bash -c "apt-get update &&
               apt-get install -y libpng-dev libjpeg-dev libonig-dev libxml2-dev zip unzip &&
               docker-php-ext-install mysqli pdo pdo_mysql &&
               apache2-foreground"

  db:
    image: mysql/mysql-server:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    platform: linux/amd64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    platform: linux/amd64
